# DevOps configuration commented out - not needed for portfolio website
# kind-config.yaml
# kind: Cluster
# apiVersion: kind.x-k8s.io/v1alpha4
# name: react-portfolio
# nodes:
#   - role: control-plane
#     extraPortMappings:
#       - containerPort: 80
#         hostPort: 8080
