apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: portfolio-role
  namespace: portfolio
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "events"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: portfolio-rolebinding
  namespace: portfolio
subjects:
- kind: ServiceAccount
  name: portfolio-sa
  namespace: portfolio
roleRef:
  kind: Role
  name: portfolio-role
  apiGroup: rbac.authorization.k8s.io
