apiVersion: v1
kind: Secret
metadata:
  name: portfolio-secrets
  namespace: portfolio
type: Opaque
stringData:
  SENTRY_DSN: "https://public@sentry.io/12345"
  OAUTH_CLIENT_SECRET: "supersecretvalue"
